# Generated by Django 6.0.7 on 2026-07-13 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(blank=True, choices=[('BE', 'Below Expectation'), ('AE', 'Approaching Expectation'), ('ME', 'Meeting Expectation'), ('EE', 'Exceeding Expectation')], max_length=2)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_growth', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_achieved', models.CharField(choices=[('BE', 'Below Expectation'), ('AE', 'Approaching Expectation'), ('ME', 'Meeting Expectation'), ('EE', 'Exceeding Expectation')], max_length=2)),
                ('teacher_comment', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_assessments', to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to=settings.AUTH_USER_MODEL)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.learningoutcome')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.term')),
            ],
            options={
                'ordering': ['-assessed_at', 'learner', 'outcome'],
                'unique_together': {('learner', 'outcome', 'term')},
            },
        ),
    ]
