# Generated by Django 6.0.7 on 2026-07-14 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencyassessment',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AssessmentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assessment_evidence/%Y/%m/')),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo of Work'), ('document', 'Document'), ('audio', 'Audio Recording'), ('video', 'Video')], max_length=10)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='assessment.competencyassessment')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
