# Generated by Django 6.0.7 on 2026-07-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='requires_course_review',
            field=models.BooleanField(default=False),
        ),
    ]
