# Generated by Django 6.0.7 on 2026-07-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorproduct',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='distributorproduct',
            name='bulk_pricing',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='distributorproduct',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
