# Generated by Django 6.0.7 on 2026-09-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_distributorwallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorprofile',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Super admins can suspend a distributor to revoke access without deleting the account.'),
        ),
    ]
