# Generated by Django 6.0.7 on 2026-07-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_teacherassignment_options_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='subject_specializations',
            field=models.ManyToManyField(blank=True, related_name='specialist_teachers', to='academics.learningarea'),
        ),
        migrations.AddField(
            model_name='user',
            name='tsc_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
