# Generated by Django 6.0.7 on 2026-09-10 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_teacherprofile'),
        ('tenants', '0002_schoolsettings_requires_course_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('ANNUAL', 'Annual Leave'), ('CASUAL', 'Casual Leave'), ('MATERNITY', 'Maternity Leave'), ('STUDY', 'Study Leave'), ('OTHER', 'Other')], default='ANNUAL', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_days', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField()),
                ('supporting_document', models.URLField(blank=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_leaves', to='tenants.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
