# Generated by Django 6.0.7 on 2026-07-20 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_teacherassignment_options_and_more'),
        ('courses', '0005_alter_lesson_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='sub_strand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='academics.substrand'),
        ),
    ]
