# Generated by Django 6.0.7 on 2026-07-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_topic_sub_strand'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_student_posts',
            field=models.BooleanField(default=False, help_text='Allow students to post in the class stream'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, help_text='Short code for students to join', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, help_text='Physical room or virtual link', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(blank=True, help_text='e.g. Section A, Group 1', max_length=50),
        ),
    ]
