# Generated by Django 6.0.7 on 2026-07-22 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_allow_student_posts_course_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='topic',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='Objectives copied from the scheme of work'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('material', 'Material'), ('question', 'Question')], default='material', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='courses.topic'),
        ),
    ]
