# Generated by Django 6.0.7 on 2026-07-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_post_attachments_post_due_date_post_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='core_competencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='pcis',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='values',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
