# Generated by Django 6.0.7 on 2026-07-15 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_distributorproduct_attributes_and_more'),
        ('shop', '0002_alter_productcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_reseller_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='linked_distributor_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_listings', to='distributor.distributorproduct'),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
