# Generated by Django 6.0.7 on 2026-09-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total commission credited to distributor(s) when this order is paid.', max_digits=10),
        ),
    ]
