# Generated by Django 6.0.7 on 2026-09-25 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_commission_earned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_name',
            field=models.CharField(blank=True, help_text='Guest delivery contact name.', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(blank=True, help_text='Guest delivery phone (also used for the M-Pesa STK push).', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='learner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learner_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Null for guest (no-account) orders.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
