# Generated by Django 6.0.7 on 2026-09-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_delivery_address_order_delivery_county_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('contact', 'Contact'), ('onboarding', 'Distributor Onboarding'), ('find_school_list', 'Find My School List'), ('upload_list', 'Upload My School List'), ('track_order', 'Track Your Order')], max_length=50)),
                ('data', models.JSONField()),
                ('file', models.FileField(blank=True, null=True, upload_to='form_submissions/')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
