# Generated by Django 6.0.7 on 2026-09-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_delivery_confirmed_at_order_dispute_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispute_evidence',
            field=models.ImageField(blank=True, null=True, upload_to='disputes/'),
        ),
    ]
