# Generated by Django 6.0.7 on 2026-09-27 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_dispute_evidence'),
        ('tenants', '0002_schoolsettings_requires_course_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tenants.school'),
        ),
    ]
