# Generated by Django 6.0.7 on 2026-09-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_tag_product_backorders_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='institution_categories',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['Pre-Primary','Primary School','University','TVET / Vocational']"),
        ),
    ]
