# Generated by Django 6.0.7 on 2026-10-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_institution_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='form_type',
            field=models.CharField(choices=[('contact', 'Contact'), ('onboarding', 'Distributor Onboarding'), ('find_school_list', 'Find My School List'), ('upload_list', 'Upload My School List'), ('track_order', 'Track Your Order'), ('lead', 'Homepage Lead'), ('demo', 'Demo Request')], max_length=50),
        ),
    ]
