# Generated by Django 6.0.7 on 2026-07-15 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_alter_teacherassignment_options_and_more'),
        ('distributor', '0002_distributorproduct_attributes_and_more'),
        ('shop', '0002_alter_productcategory_unique_together_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('allow_external_purchase', models.BooleanField(default=True)),
                ('preferred_source', models.CharField(choices=[('school', 'School'), ('distributor', 'Distributor')], default='school', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_items', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_items', to='tenants.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_items', to='academics.term')),
            ],
            options={
                'ordering': ['class_level__order', 'name'],
                'unique_together': {('school', 'name', 'class_level', 'term')},
            },
        ),
        migrations.CreateModel(
            name='RequiredItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('school', 'School'), ('distributor', 'Distributor')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('delivery_available', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_item_options', to='distributor.distributorprofile')),
                ('linked_distributor_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_item_options', to='distributor.distributorproduct')),
                ('linked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_item_options', to='shop.product')),
                ('required_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='requirements.requireditem')),
            ],
            options={
                'ordering': ['source_type', 'price'],
            },
        ),
    ]
