# Generated by Django 6.0.7 on 2026-07-14 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='tenants.school')),
                ('trainers', models.ManyToManyField(blank=True, related_name='trained_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClubSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(help_text='What was taught in this session', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_club_sessions', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clubs.club')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_sessions', to='tenants.school')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'club__name'],
            },
        ),
    ]
