# Generated by Django 6.0.7 on 2026-07-13 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('curriculum_design', 'KICD Curriculum Design'), ('sample_scheme', 'Sample Scheme of Work')], max_length=20)),
                ('file', models.FileField(upload_to='reference_documents/%Y/')),
                ('source_note', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_docs', to='academics.learningarea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_docs', to='tenants.school')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', 'learning_area'],
            },
        ),
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Auto-generated Draft'), ('in_progress', 'Being Edited'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='academics.learningarea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='tenants.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='academics.stream')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='academics.term')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'learning_area', 'term', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='SchemeWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('specific_learning_outcomes', models.TextField()),
                ('key_inquiry_question', models.TextField(blank=True)),
                ('learning_experiences', models.TextField(blank=True)),
                ('learning_resources', models.TextField(blank=True)),
                ('assessment_method', models.TextField(blank=True)),
                ('reflection', models.TextField(blank=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='curriculum.schemeofwork')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_weeks', to='academics.strand')),
                ('sub_strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_weeks', to='academics.substrand')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
    ]
