# Generated by Django 6.0.7 on 2026-07-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_schemeweek_course_schemeweek_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeweek',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
