# Generated by Django 6.0.7 on 2026-07-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_schemeweek_lesson_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeofwork',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='scheme_uploads/'),
        ),
    ]
