# Generated by Django 6.0.7 on 2026-07-14 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherassignment',
            options={'ordering': ['-term__start_date', 'stream__grade__order', 'stream__name', 'role', 'learning_area__name']},
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='role',
            field=models.CharField(choices=[('subject_teacher', 'Subject Teacher'), ('class_teacher', 'Class Teacher'), ('assistant_teacher', 'Assistant/TA')], default='subject_teacher', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.term'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='learning_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.learningarea'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'stream', 'learning_area', 'term')},
        ),
        migrations.CreateModel(
            name='LearnerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_learner_groups', to=settings.AUTH_USER_MODEL)),
                ('learning_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_groups', to='academics.learningarea')),
                ('members', models.ManyToManyField(related_name='learner_groups', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_groups', to='tenants.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academics.stream')),
            ],
            options={
                'ordering': ['stream__grade__order', 'stream__name', 'name'],
                'unique_together': {('school', 'stream', 'name')},
            },
        ),
    ]
