# Generated by Django 6.0.7 on 2026-07-22 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('tenants', '0002_schoolsettings_requires_course_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='note',
            field=models.TextField(blank=True, help_text='Absence reason, late excuse, or doctor note reference'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='excused_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused'), ('SICK_LEAVE', 'Sick Leave'), ('AUTHORIZED_ABSENCE', 'Authorized Absence')], max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ABSENT_ALERT', 'Absent Alert'), ('LOW_ATTENDANCE', 'Low Attendance Warning'), ('SICK_LEAVE', 'Sick Leave Notification')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications', to='tenants.school')),
                ('sent_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_notifications_received', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
